sudo: required

services:
    - docker

git:
    depth: 3

cache:
    directories:
        - js/leveros/node_modules
        - js/leveros-common/node_modules

language: go

env:
    global:
        - DOCKER_COMPOSE_VERSION=1.7.1
    matrix:
        - USE_GO=0
        - USE_GO=1

go: 1.6

before_install:
    - sudo apt-get -qq update
    - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -y docker-engine
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose && sudo mv docker-compose /usr/local/bin/
    - wget https://github.com/google/protobuf/releases/download/v3.0.0-beta-2/protoc-3.0.0-beta-2-$TRAVIS_OS_NAME-x86_64.zip && sudo unzip protoc-3.0.0-beta-2-$TRAVIS_OS_NAME-x86_64.zip protoc -d /usr/local/bin/ && sudo chmod +x /usr/local/bin/protoc

install:
    - npm install -g grunt-cli
    - cd js/leveros-common && npm install && cd ../..
    - cd js/leveros && npm link ../leveros-common && npm install && cd ../..
    - go get -u github.com/golang/lint/golint
    - go get -u github.com/golang/protobuf/protoc-gen-go
    - go get -u github.com/tools/godep

script:
    - make test
    - cd js/leveros-common && grunt lint && grunt && cd ../..
    - cd js/leveros && grunt lint && grunt && cd ../..
    - make clean-all
    - if [ "$USE_GO" -eq "1" ]; then make RUN_BACKGROUND=1 run ; else make RUN_BACKGROUND=1 fastrun ; fi && sleep 3 && make systest

after_script:
    - docker logs leverosconsul
    - docker logs leverosaerospike
    - docker logs leverosnghttpxext
    - docker logs leveroshost
